# Test Configuration
test:
  # Loop test configuration
  loop:
    enabled: false  # Enable loop test
    count: 1       # Loop count

  # Performance test configuration
  performance:
    total_size: 128  # Total data size (MB)
    block_size: 1    # Block size (MB)
    iterations: 3    # Average times

# UI Configuration
ui:
  always_on_top: true  # Keep window always on top

# Logger Configuration
logger:
  level: INFO  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL 
