# Card Configuration
card:
  sd_express_model: ""  # SD Express card model name, empty for automatic detection
  sd4_disable: false    # Whether to disable SD 4.0 mode and reinitialize as SD 3.0
  registry_path: "SYSTEM\\CurrentControlSet\\Services\\bhtsddr\\GG8"  # Registry path for SD host controller
  registry_item: "sd_card_mode_dis"  # Registry item name for card configuration

# Test Configuration
test:
  # Loop test configuration
  loop:
    enabled: false  # Enable loop test
    count: 1       # Loop count

  # Performance test configuration
  performance:
    total_size: 128  # Total data size (MB)
    block_size: 1    # Block size (MB)
    iterations: 3    # Average times

# UI Configuration
ui:
  always_on_top: true  # Keep window always on top

# Logger Configuration
logger:
  level: INFO  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL 
